### PR TITLE
generate valid proofs

### PR DESCRIPTION
**Pull request by bcuz**
finding valid proofs within 40 seconds. so as long as the algo is correct here, this should be close to production ready. the cooldown time in this file will be lowered from 45 sec to 15 once we buy our names

How the output is looking right now:
Selection_012

### CODE REVIEW

**Comment by bcuz** [comment]
[more work on mining](https://trello.com/c/8yk2gwer/34-more-work-on-mining)

**Review by jthicks91 — APPROVED** [review]
Looks good to me! (That cooldown period is brutal, haha.)

**Comment by bcuz** [comment]
i think i can make this more efficient in terms of cooldown, but for now it's good as is

**Comment by jthicks91** [comment]
Agreed.

**Pull request merged**
